version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole-exporter
    secrets:
      - pihole_api_token
    environment:
      - PIHOLE_PROTOCOL=http
      - PIHOLE_HOSTNAME=10.0.4.137
      - PIHOLE_PORT=80
      - PIHOLE_API_TOKEN=/run/secrets/pihole_api_token
      - PORT=9617
    ports:
      - "9617:9617"

volumes:
  prometheus:

secrets:
  pihole_api_token:
    file: ./pihole-api-token.txt
