version: "3.8"

services:
  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole-exporter
    environment:
      - PIHOLE_PROTOCOL=http
      - PIHOLE_HOSTNAME=10.0.4.137
      - PIHOLE_PORT=80
      - PIHOLE_API_TOKEN=<token>
      - PORT=9617
    ports:
      - "9617:9617"
