services:
  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole-exporter
    network_mode: "host"
    environment:
      PIHOLE_PROTOCOL: http
      PIHOLE_HOSTNAME: 127.0.0.1
      PIHOLE_PORT: 80
      PIHOLE_API_TOKEN: <REPLACE_ME>
      PORT: 9617
    ports:
      - "9617:9617"
