version: "3.8"

services:
  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole-exporter
    secrets:
      - pihole_api_token
    environment:
      - PIHOLE_PROTOCOL=http
      - PIHOLE_HOSTNAME=localhost
      - PIHOLE_PORT=80
      - PIHOLE_API_TOKEN=/run/secrets/pihole_api_token
      - PORT=9617
    ports:
      - "9617:9617"

secrets:
  pihole_api_token:
    file: ./pihole-api-token.txt
