version: "3.8"

services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    network_mode: host
    pid: host
    restart: unless-stopped
    ports:
      - "9100:9100"
